name: hospitalink
description: "Smart Healthcare Queue System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  http: ^1.2.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.0.1
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  awesome_notifications: ^0.9.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
